### ISSUE TITLE
How can we use it?

### ISSUE THREAD

**Issue by SharafatKarim** [Ezykill/wiki_random#1]
Please give us some guide to use it

**Comment by timotheeMM** [comment]
Hi @SharafatKarim,
You must install the package with `pip install wiki-random` and then import it into your code with `import wiki_random'. Finally, you can use the get_wiki_random() function with `title, url = wiki_random.get_wiki_random()`

**Comment by SharafatKarim** [comment]
Thanks a lot!
Please add this information in the readme so that others can easily learn about it.

sincerely appreciate it ❤️.

**Comment by timotheeMM** [comment]
@SharafatKarim
:blush: I’m not the repo owner so I can’t change it.
Congratulations for your contributions, your contribution graphic is all green! :smile:

**Comment by SharafatKarim** [comment]
oh! ok ok bro 🌸

btw, 
my contribution graph -> GitHub action fact 😅

**Comment by timotheeMM** [comment]
😂😂😂
